name: Discord Notifications

on:
  push:  # Trigger on push events
    branches:
      - '*'  # Matches all branches
  create:  # Trigger on branch creation
    branches:
      - '*'
  pull_request:  # Trigger on pull request events
    types: [opened, closed, reopened]
  issues:  # Trigger on issue events
    types: [opened, closed, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_EVENT: ${{ github.event_name }}
        run: |
          MESSAGE=""

          case $GITHUB_EVENT in
            push)
              MESSAGE="New commit pushed to branch ${{ github.ref_name }} by ${{ github.actor }}"
              ;;
            create)
              MESSAGE="New branch created: ${{ github.ref }} by ${{ github.actor }}"
              ;;
            pull_request)
              ACTION="${{ github.event.action }}"
              if [ "$ACTION" = "opened" ]; then
                MESSAGE="New pull request opened by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
              elif [ "$ACTION" = "closed" ]; then
                MESSAGE="Pull request closed by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}"
              fi
              ;;
            issues)
              MESSAGE="Issue ${{ github.event.action }} by ${{ github.actor }}: ${{ github.event.issue.html_url }}"
              ;;
          esac

          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
